language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: QL4RV84RwwJYyrZ9eZmRsDIW4fbSJPVGt27zLfl7hw6jsooyySRNfocF1I8ZzAIIhB6NL5D43WoxOYrpG1N6EmPvcq8fcjH7wkdPEm7WU3L6gwdHApmMCSlax1p75lK15kha3YfXYNYl9M49SowkhmssupWmOCOHgtXtHGoCxYI7PpU6ScT4fGRdBKLQ65keghCxCpfz84smTaqLF4vK4s6qhQTsh+FFYr2jc0KdZmyve2M9u75VE6ETMpn+v8SOLHbodo2eFfCLYIMyrYxU5Gz9sXOxxlO1mY99FeeRIqj72WsgjN0yWx0EAlDzTvm74UzpzKeXaqa9MBiWnRY2gjKW142FWLN7viY4S7RH3OTLlvqC1idkaDCtjuwNKLtP9a1Do5Mvjgp+y2oPHN9aXHNmFoW2yVFkK+iQOeyZ0iW/lMDzRsqQnzt7uPgbLH0eU+cxCpNvh5C/xCu1rE/iFyytMdvVEYj3CnvZK2vBkoTc4ch2k2YGUV+g1R+sw3LB3in4I5p31QCCBNeYMrhby1B95p/B/1y5gvEPhiIi6Nl1HQSVNh2H+V2gXkI1XURJaT5JCN8O7o6/UTYvyDPRPu6N4XR9KiJc+e4uhQONN4nOIb315AiOOtuwDUF415lvXUIopwGcluqjjnmhW+7xwe0/biZPYi96wFjPIMbGAuQ=
